### Data Formatting

In [42]:
import numpy as np
import pandas as pd

#
# Change these to switch around parameters
#

set_size = 4 # Number of consecutive days in a row
data_column = 1 # Index of column to use (S&P - 1)




# Load data from current directory
data = pd.read_csv('./data_stocks.csv')

data = data.values

# Pull specified column of data
snp = data[:,np.arange(data_column, data_column + 1)]

data_set = []

# Loop over full set
for idx in range(len(snp)):

    row = []

    # Check if our range goes over the list length
    if idx + set_size > len(snp):
        break

    # Build a row starting at current
    # index to index + set_size
    for v in range(set_size):
        is_last = v == (set_size - 1)
        
        current_index = idx + v
        current_value = snp[current_index][0]

        # Produce last day predictor if it's the last
        # iteration
#         if is_last:
#             last_value = row[-1]
#             diff = current_value - last_value
            
#             # Reults in either [-1,0,1]
#             predictor = 0 if diff == 0 else (diff/abs(diff))
#             row.append(predictor)
            
#         # Otherwise append the value
#         else:
#             row.append(current_value)

        row.append(current_value)


    row = np.array(row)
    data_set.append(row)


data_set = np.asarray(data_set)

fmt = {'float_kind':'{:0.2f}'.format}
np.set_printoptions(suppress=True, formatter=fmt)

# Prints top 10 records for quick confirmation
print(data_set[0:10])

np.savetxt("output.csv", data_set, delimiter=",", fmt="%10.2f")
print("\n\nSaved data to 'output.csv'")

[[2363.61 2364.10 2362.68 2364.31]
 [2364.10 2362.68 2364.31 2364.85]
 [2362.68 2364.31 2364.85 2365.62]
 [2364.31 2364.85 2365.62 2365.20]
 [2364.85 2365.62 2365.20 2365.29]
 [2365.62 2365.20 2365.29 2364.32]
 [2365.20 2365.29 2364.32 2364.64]
 [2365.29 2364.32 2364.64 2364.58]
 [2364.32 2364.64 2364.58 2364.48]
 [2364.64 2364.58 2364.48 2365.23]]


Saved data to 'output.csv'


### Network

In [44]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt


data = pd.read_csv('./output.csv')

data = data.values
np.random.shuffle(data)

# Split data into inputs and outputs
# inputs = data[:, np.arange(0,2)]
# outputs = data[:, 3]

# Scale Data to [-1,1]
scaler = MinMaxScaler(feature_range=(-1, 1))
# scaled_input = scaler.fit_transform(inputs)

scaled_data = scaler.fit_transform(data)
# Split data into inputs and outputs
inputs = scaled_data[:, np.arange(0,2)]
outputs = scaled_data[:, 3]

# Split Data into 80% train, 20% test
cutoff = int(np.floor(0.8 * len(scaled_input)))

train_inputs = scaled_input[:cutoff]
train_outputs = outputs[:cutoff]

test_inputs = scaled_input[cutoff + 1:]
test_outputs = outputs[cutoff + 1:]

# Setup placeholders for input and output
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None])
            
# Build basic network with sigmoid activation
# and using the pre-built dense layer
network = tf.layers.dense(X, units=1, activation=tf.nn.sigmoid)
network = tf.layers.dense(network, units=1, activation=tf.nn.sigmoid)
cost = tf.reduce_mean((network - Y)**2)
# cost = tf.reduce_mean(tf.squared_difference(network, Y))

optimizer = tf.train.RMSPropOptimizer(0.01).minimize(cost)
init = tf.global_variables_initializer()

batch_size = 256

with tf.Session() as sess:
    sess.run(init)
   
    for epoch in range(100):
        shuffled_indices = np.random.permutation(np.arange(len(train_inputs)))
        train_inputs = train_inputs[shuffled_indices]
        train_outputs = train_outputs[shuffled_indices]
        
        for i in range(len(train_outputs // batch_size)):
            start = i * batch_size
            batch_x = train_inputs[start:start + batch_size]
            batch_y = train_outputs[start:start + batch_size]
            
            sess.run([optimizer, cost], feed_dict={X: batch_x, Y: batch_y})
   
        print(sess.run(cost, feed_dict={X: train_inputs, Y: train_outputs}))
        print(sess.run(cost, feed_dict={X: test_inputs, Y: test_outputs}))
        
        
        
        

    



0.136142
0.238541
0.132395
0.238559
0.133501
0.238555
0.132549
0.238457
0.132662
0.238521
0.131925
0.238652
0.132038
0.238636


KeyboardInterrupt: 

### Visualization Example

In [1]:
import tensorflow as tf


a = tf.add(1, 2, name="Add_these_numbers")
b = tf.multiply(a, 3)
c = tf.add(4, 5, name="And_These_ones")
d = tf.multiply(c, 6, name="Multiply_these_numbers")
e = tf.multiply(4, 5, name="B_add")
f = tf.div(c, 6, name="B_mul")
g = tf.add(b, d)
h = tf.multiply(g, f)
s = tf.sigmoid(float(g))
#lstm = tf.contrib.rnn.BasicLSTMCell(5)


with tf.Session() as sess:
    print(sess.run(s))

with tf.Session() as sess:
    writer = tf.summary.FileWriter("output", sess.graph)
    print(sess.run(h))
    writer.close()

TypeError: float() argument must be a string or a number, not 'Tensor'

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import os

data = pd.read_csv('./project3/data_stocks.csv')
print (data[1])
data = data.values
print (data[1])
n = data.shape[0]
p = data.shape[1]

pyplot.plot(data['SP500'])

#ten previous prices
sequence_length = 10

input_dimension = 1
data = tf.placeholder(tf.float32, [None, 20,1]) #Number of examples, number of input, dimension of each input
target = tf.placeholder(tf.float32, [None, 21])

In [35]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import os

scaler = MinMaxScaler(feature_range=(-1, 1))
#scaler.fit(data)

#data = pd.read_csv('./project3/data_stocks.csv')
#print (data['SP500'][0:100])
#data = data.values
#print (data)
#n = data.shape[0]
#p = data.shape[1]

#print (data[2])


#scaler = MinMaxScaler(feature_range=(-1, 1))
#scaler.fit(data['SP500'])
days = [1491226740.00,1491226800.00,1491226860.00,1491226920.00]
#days = [2363.6101, 2364.1001, 2362.6799, 2364.8501]
print (type(days))
scaler.fit(days)
days = scaler.transform(days)
print (type(list(days)))
days = list(days)
print (days)
day2 = days[0:3]
print (day2)
print (days[3])
day3 = days[3]
x = tf.constant([day2, [2, 3, 4], [3, 4, 5], [4, 5, 6]], dtype=tf.float32)
y_true = tf.constant([[day3], [5], [6], [7]], dtype=tf.float32)

previous = tf.constant([[0, 0,0,0]],dtype=tf.float32)
tomorrow = tf.constant([[0]], dtype=tf.float32)


#x = tf.constant([[2363.6101], [2364.1001], [2362.6799], [2364.3101]], dtype=tf.float32)
#y_true = tf.constant([[2364.1001], [2362.6799], [2364.3101], [2364.8501]], dtype=tf.float32)




#yesterday = data['SP500']
#today = data['SP500'][1:6]
#print (yesterday)
#print (yesterday)

linear_model = tf.layers.Dense(units=1)

y_pred = linear_model(x)
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print (sess.run(y_pred))
for i in range(100):
  _, loss_value = sess.run((train, loss))
  #print (sess.run(y_pred))
  print(loss_value)

print(sess.run(y_pred))


scaler = MinMaxScaler(feature_range=(2362.6799, 2364.8501))
thing = [0.11891884, .3]
scaler.fit(thing)
thing = scaler.transform(thing)
print (thing)

<class 'list'>
<class 'list'>
[-1.0, -0.3333333320915699, 0.33333333395421505, 1.0]
[-1.0, -0.3333333320915699, 0.33333333395421505]
1.0


//anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:324: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
//anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:359: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


[[ 0.20026046]
 [-0.82043386]
 [-1.1406693 ]
 [-1.4609053 ]]
39.273277
1.9885426
0.39249957
0.31693798
0.3063346
0.29868105
0.29133132
0.2841685
0.27718318
0.2703708
0.26372698
0.2572477
0.25092882
0.24476631
0.23875639
0.23289524
0.22717918
0.2216045
0.21616793
0.21086589
0.20569518
0.20065235
0.1957343
0.19093822
0.18626066
0.18169905
0.17725019
0.17291155
0.16868028
0.16455378
0.1605293
0.15660457
0.15277694
0.14904407
0.1454036
0.14185323
0.13839075
0.1350139
0.13172072
0.128509
0.12537685
0.12232228
0.11934315
0.116437845
0.113604546
0.11084127
0.10814643
0.105518185
0.1029551
0.10045555
0.09801775
0.09564029
0.093321726
0.09106047
0.0888554
0.086704664
0.08460732
0.082561746
0.08056692
0.078621395
0.07672408
0.07487373
0.07306916
0.071309224
0.06959289
0.06791901
0.06628662
0.06469467
0.063142
0.061627768
0.06015113
0.058710936
0.05730642
0.05593663
0.054600883
0.0532981
0.052027464
0.050788417
0.04958002
0.048401378
0.047252078
0.04613127
0.045038097
0.043971907
0.042932253
0.04

//anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:324: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
//anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:359: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


In [ ]:
lstm = tf.contrib.rnn.BasicLSTMCell(5)

with tf.Session() as sess:
    writer = tf.summary.FileWriter("output", sess.graph)
    print(sess.run(lstm))
    writer.close()


In [ ]:
import tensorflow as tf

day1 = tf.constant(100, dtype=tf.float32)
day2 = tf.constant(150, dtype=tf.float32)
s = tf.sigmoid(day1)
y_true = tf.constant(200, dtype=tf.float32)
sess = tf.Session()
print (sess.run(s))